
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '904DE629A081E6E3E6BC589C3DEABBBF'
    
_lr_action_items = {'COMMA':([6,8,9,13,],[-8,11,12,-9,]),'DCL':([0,1,2,10,],[3,3,-3,-4,]),'ID':([3,11,12,],[6,13,6,]),'$end':([1,2,4,5,10,],[-1,-3,0,-2,-4,]),'SMC':([6,7,8,9,13,14,],[-8,10,-7,-5,-9,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([3,12,],[9,9,]),'declaration_list':([3,12,],[7,14,]),'id_list':([3,12,],[8,8,]),'statement':([0,1,],[1,5,]),'declaration_statement':([0,1,],[2,2,]),'program':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','lyaParser.py',78),
  ('program -> statement statement','program',2,'p_program','lyaParser.py',79),
  ('statement -> declaration_statement','statement',1,'p_statement','lyaParser.py',82),
  ('declaration_statement -> DCL declaration_list SMC','declaration_statement',3,'p_declaration_statement','lyaParser.py',85),
  ('declaration_list -> declaration','declaration_list',1,'p_declaration_list','lyaParser.py',89),
  ('declaration_list -> declaration COMMA declaration_list','declaration_list',3,'p_declaration_list','lyaParser.py',90),
  ('declaration -> id_list','declaration',1,'p_declaration','lyaParser.py',93),
  ('id_list -> ID','id_list',1,'p_id_list','lyaParser.py',99),
  ('id_list -> id_list COMMA ID','id_list',3,'p_id_list','lyaParser.py',100),
]
